# Generated by Django 3.1.4 on 2021-02-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_base', '0002_auto_20210212_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testattempttask',
            name='answer',
            field=models.CharField(max_length=255, null=True, verbose_name='Answer'),
        ),
    ]
